# Generated by Django 5.2.17 on 2026-09-03 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CanteenMenu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日付")),
                ("menu_text", models.TextField(verbose_name="メニュー内容")),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "手動登録"), ("scraped", "自動取得")],
                        default="manual",
                        max_length=10,
                        verbose_name="取得元",
                    ),
                ),
            ],
            options={
                "verbose_name": "学食メニュー",
                "verbose_name_plural": "学食メニュー",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "在室"), ("absent", "不在")],
                        default="absent",
                        max_length=10,
                        verbose_name="状態",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_status",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "在室状況",
                "verbose_name_plural": "在室状況",
            },
        ),
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("body", models.TextField(verbose_name="本文")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "下書き"), ("published", "公開")],
                        default="draft",
                        max_length=10,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="公開日時"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投稿者",
                    ),
                ),
            ],
            options={
                "verbose_name": "News記事",
                "verbose_name_plural": "News記事",
                "ordering": ["-published_at", "-id"],
            },
        ),
    ]
