# Generated by Django 5.2.17 on 2026-09-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspost",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("published_at"), descending=True, nulls_first=True
                    ),
                    "-id",
                ],
                "verbose_name": "News記事",
                "verbose_name_plural": "News記事",
            },
        ),
    ]
