# Generated by Django 5.2.17 on 2026-09-06 04:32

import community.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_alter_newspost_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NfcTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="例: 入り口（右扉）",
                        max_length=50,
                        verbose_name="名称",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="設置場所"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=community.models.generate_nfc_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="トークン",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "NFCタグ",
                "verbose_name_plural": "NFCタグ",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("enter", "入室"), ("exit", "退室")],
                        max_length=10,
                        verbose_name="種別",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("web", "画面から"), ("nfc", "NFCタグ")],
                        default="web",
                        max_length=10,
                        verbose_name="登録元",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="記録日時"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="community.nfctag",
                        verbose_name="NFCタグ",
                    ),
                ),
            ],
            options={
                "verbose_name": "入退室履歴",
                "verbose_name_plural": "入退室履歴",
                "ordering": ["-recorded_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "-recorded_at"],
                        name="community_a_user_id_da6a98_idx",
                    )
                ],
            },
        ),
    ]
