# Generated by Django 5.2.17 on 2026-09-06 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_nfctag_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canteenmenu",
            name="menu_text",
            field=models.TextField(
                blank=True,
                help_text="定食・丼以外の情報（麺コーナー、臨時休業など）",
                verbose_name="補足",
            ),
        ),
        migrations.CreateModel(
            name="CanteenMenuItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("set_meal", "定食"), ("donburi", "アラカルト丼")],
                        max_length=10,
                        verbose_name="区分",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="品名")),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="並び順"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="community.canteenmenu",
                        verbose_name="学食メニュー",
                    ),
                ),
            ],
            options={
                "verbose_name": "学食メニューの品目",
                "verbose_name_plural": "学食メニューの品目",
                "ordering": ["category", "position", "id"],
            },
        ),
    ]
