# Generated by Django 5.2.17 on 2026-09-06 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0005_alter_canteenmenu_menu_text_canteenmenuitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="canteenmenu",
            name="registered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="最後に登録・更新した人。研究室の共有情報のため、退会しても献立は残す",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registered_canteen_menus",
                to=settings.AUTH_USER_MODEL,
                verbose_name="登録者",
            ),
        ),
    ]
