# Generated by Django 5.2.17 on 2026-09-06 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_canteenmenu_registered_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例: 会議室A", max_length=50, verbose_name="名称"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="場所"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="定員"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="利用可")),
            ],
            options={
                "verbose_name": "会議室",
                "verbose_name_plural": "会議室",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoomReservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purpose", models.CharField(max_length=100, verbose_name="用件")),
                ("start_at", models.DateTimeField(verbose_name="開始日時")),
                ("end_at", models.DateTimeField(verbose_name="終了日時")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="community.meetingroom",
                        verbose_name="会議室",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="予約者",
                    ),
                ),
            ],
            options={
                "verbose_name": "会議室の予約",
                "verbose_name_plural": "会議室の予約",
                "ordering": ["start_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["room", "start_at"],
                        name="community_r_room_id_7e3d51_idx",
                    )
                ],
            },
        ),
    ]
