# Generated by Django 5.2.17 on 2026-09-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0008_initial_meeting_rooms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meetingroom",
            options={
                "ordering": ["position", "name"],
                "verbose_name": "会議室",
                "verbose_name_plural": "会議室",
            },
        ),
        migrations.AddField(
            model_name="meetingroom",
            name="position",
            field=models.PositiveIntegerField(
                default=0,
                help_text="小さいほど先に表示する。同じ値のときは名称順",
                verbose_name="並び順",
            ),
        ),
        migrations.AlterField(
            model_name="meetingroom",
            name="location",
            field=models.CharField(
                blank=True, help_text="例: B307", max_length=100, verbose_name="場所"
            ),
        ),
        migrations.AlterField(
            model_name="meetingroom",
            name="name",
            field=models.CharField(
                help_text="例: 全体ミーティングルーム",
                max_length=50,
                verbose_name="名称",
            ),
        ),
    ]
