# Generated by Django 5.2.17 on 2026-09-03 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                (
                    "category",
                    models.CharField(
                        choices=[("lab", "研究室サーバー"), ("dept", "学科サーバー")],
                        max_length=10,
                        verbose_name="種別",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="設置場所"
                    ),
                ),
            ],
            options={
                "verbose_name": "サーバー",
                "verbose_name_plural": "サーバー",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServerLongTermRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="利用開始日")),
                ("end_date", models.DateField(verbose_name="利用終了日")),
                ("reason", models.TextField(verbose_name="利用理由")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "申請中"),
                            ("approved", "承認"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="承認日時"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="承認者",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="long_term_requests",
                        to="servers.server",
                        verbose_name="サーバー",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申請者",
                    ),
                ),
            ],
            options={
                "verbose_name": "サーバー長期利用申請",
                "verbose_name_plural": "サーバー長期利用申請",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ServerUsageSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(db_index=True, verbose_name="取得日時"),
                ),
                ("cpu_percent", models.FloatField(verbose_name="CPU使用率(%)")),
                ("memory_percent", models.FloatField(verbose_name="メモリ使用率(%)")),
                ("disk_percent", models.FloatField(verbose_name="ディスク使用率(%)")),
                (
                    "gpu_percent",
                    models.FloatField(
                        blank=True, null=True, verbose_name="GPU使用率(%)"
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_snapshots",
                        to="servers.server",
                        verbose_name="サーバー",
                    ),
                ),
            ],
            options={
                "verbose_name": "サーバー利用状況",
                "verbose_name_plural": "サーバー利用状況",
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["server", "-captured_at"],
                        name="servers_ser_server__71faaf_idx",
                    )
                ],
            },
        ),
    ]
