# Generated by Django 5.2.17 on 2026-09-03 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobHuntingStory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="研究室内に公開"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_hunting_stories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投稿者",
                    ),
                ),
            ],
            options={
                "verbose_name": "就活体験記",
                "verbose_name_plural": "就活体験記",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ObVisitRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desired_date", models.DateField(verbose_name="希望日")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "調整中"),
                            ("confirmed", "確定"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="ステータス",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ob_visit_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申請者",
                    ),
                ),
            ],
            options={
                "verbose_name": "OB訪問予約",
                "verbose_name_plural": "OB訪問予約",
                "ordering": ["desired_date"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="タイトル")),
                ("description", models.TextField(verbose_name="説明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "未着手"),
                            ("in_progress", "対応中"),
                            ("done", "完了"),
                        ],
                        default="open",
                        max_length=12,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        default="medium",
                        max_length=10,
                        verbose_name="優先度",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="起票者",
                    ),
                ),
            ],
            options={
                "verbose_name": "チケット",
                "verbose_name_plural": "チケット",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="本文")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投稿者",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="office.ticket",
                        verbose_name="チケット",
                    ),
                ),
            ],
            options={
                "verbose_name": "チケットコメント",
                "verbose_name_plural": "チケットコメント",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TravelExpenseRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.CharField(max_length=100, verbose_name="出張先"),
                ),
                ("purpose", models.TextField(verbose_name="目的")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="金額(円)"
                    ),
                ),
                ("travel_start", models.DateField(verbose_name="出張開始日")),
                ("travel_end", models.DateField(verbose_name="出張終了日")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "申請中"),
                            ("approved", "承認"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_travel_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="承認者",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_expense_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申請者",
                    ),
                ),
            ],
            options={
                "verbose_name": "出張費申請",
                "verbose_name_plural": "出張費申請",
                "ordering": ["-id"],
            },
        ),
    ]
