# Generated by Django 5.2.17 on 2026-09-03 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferencePrep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conference_name",
                    models.CharField(max_length=100, verbose_name="学会名"),
                ),
                ("deadline", models.DateField(verbose_name="締切日")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_preps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="担当者",
                    ),
                ),
            ],
            options={
                "verbose_name": "学会準備",
                "verbose_name_plural": "学会準備",
                "ordering": ["deadline"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceChecklistItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=200, verbose_name="項目")),
                ("done", models.BooleanField(default=False, verbose_name="完了")),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="research.conferenceprep",
                        verbose_name="学会準備",
                    ),
                ),
            ],
            options={
                "verbose_name": "学会準備チェックリスト項目",
                "verbose_name_plural": "学会準備チェックリスト項目",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                ("content", models.TextField(verbose_name="本文")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="カンマ区切りで入力",
                        max_length=200,
                        verbose_name="タグ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "研究日記",
                "verbose_name_plural": "研究日記",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="research_di_user_id_80ebe5_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScheduleEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="タイトル")),
                ("start_at", models.DateTimeField(verbose_name="開始日時")),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="終了日時"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("milestone", "マイルストーン"), ("task", "タスク")],
                        max_length=10,
                        verbose_name="種別",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_events",
                        to="research.conferenceprep",
                        verbose_name="関連する学会準備",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="空欄の場合は研究室共通の予定として扱う",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="担当者",
                    ),
                ),
            ],
            options={
                "verbose_name": "研究スケジュール",
                "verbose_name_plural": "研究スケジュール",
                "ordering": ["start_at"],
                "indexes": [
                    models.Index(
                        fields=["start_at"], name="research_sc_start_a_a91819_idx"
                    )
                ],
            },
        ),
    ]
