# Generated by Django 5.2.17 on 2026-09-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="visibility",
            field=models.CharField(
                choices=[("private", "非公開（自分のみ）"), ("lab", "研究室内に公開")],
                default="private",
                help_text="研究室内に公開すると、他のメンバーも閲覧できます",
                max_length=10,
                verbose_name="公開範囲",
            ),
        ),
    ]
