# Generated by Django 5.2.17 on 2026-09-04 12:01

import django.db.models.deletion
import research.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_diaryentry_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=research.models.diary_attachment_path,
                        verbose_name="ファイル",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="元のファイル名"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添付日時"),
                ),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="research.diaryentry",
                        verbose_name="研究日記",
                    ),
                ),
            ],
            options={
                "verbose_name": "研究日記の添付ファイル",
                "verbose_name_plural": "研究日記の添付ファイル",
                "ordering": ["uploaded_at", "id"],
            },
        ),
    ]
