# Generated by Django 5.2.17 on 2026-09-04 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0004_diarycomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleevent",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                help_text="選んだメンバーのスケジュールにもこの予定が表示されます",
                related_name="participating_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="参加者",
            ),
        ),
    ]
