# Generated by Django 5.2.17 on 2026-09-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_scheduleevent_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("appointment", "予定"),
                    ("task", "タスク"),
                    ("milestone", "マイルストーン"),
                ],
                default="appointment",
                help_text="打ち合わせなど時間が決まっているものは「予定」",
                max_length=15,
                verbose_name="種別",
            ),
        ),
    ]
