# Generated by Django 5.2.17 on 2026-09-05 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0006_alter_scheduleevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_diaries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="いいね",
            ),
        ),
    ]
